### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by xXRyzen** [Johnmacrocraft/NotMeXboxLiveAuth#1]
Hello, how exactly does this plugin work? ive added a player to the xboxlive list and the person still gets prompted to sign into xbox live, maybe im missing something, please explain how it works, thanks!

**Comment by Johnmacrocraft** [comment]
You mean that client-side Xbox Live sign in prompt, right? There are few ways to bypass it, but I recommend using dktapps' proxy. Download run.php at [here](https://gist.github.com/dktapps), and then run it using PHP. If you type server address and port it'll run a local server. As Minecraft doesn't block people playing local server without signing into Xbox Live, you can connect to that local server. Local server will connect to the server you've typed at the above.

You can also try this way:
1. Run a local PocketMine-MP server.
2. Join it.
3. Use transferserver command to transfer to the server you want to use this plugin.

**Comment by Johnmacrocraft** [comment]
Closing as reporter didn't give any response.
