### ISSUE TITLE
Idea.

### ISSUE THREAD

**Issue by Karanztez** [Johnmacrocraft/NotMeXboxLiveAuth#4]
You can share aside from Port 19132
to Port 19133

**Comment by Karanztez** [comment]
19132 and into the transfer to 19133, causing the xbox auth to bounce up

**Comment by Johnmacrocraft** [comment]
It (I assume you mean that Xbox login bypass proxy by dktapps) would work if the server is local since the game doesn't require Xbox login for it. It wouldn't work for remote servers, though.
